package main

const COMMAND_PING = "PING"
const COMMAND_ECHO = "ECHO"
const COMMAND_GET = "GET"
const COMMAND_SET = "SET"
const COMMAND_EXISTS = "EXISTS"
const COMMAND_DELETE = "DEL"
const COMMAND_INCREMENT = "INCR"
const COMMAND_DECREMENT = "DECR"
const COMMAND_LPUSH = "LPUSH"
const COMMAND_RPUSH = "RPUSH"

const COMMAND_PING_EXPECTED_SIZE = 1
const COMMAND_ECHO_EXPECTED_SIZE = 2
const COMMAND_GET_EXPECTED_SIZE = 2
const COMMAND_SET_EXPECTED_SIZE = 3
const COMMAND_SET_WITH_TIMEOUT_EXPECTED_SIZE = 5
const COMMAND_EXISTS_EXPECTED_SIZE = 2
const COMMAND_DELETE_EXPECTED_SIZE = 2
const COMMAND_INCREMENT_EXPECTED_SIZE = 2
const COMMAND_DECREMENT_EXPECTED_SIZE = 2
const COMMAND_LPUSH_EXPECTED_SIZE = 3
const COMMAND_RPUSH_EXPECTED_SIZE = 3

const COMMAND_INDEX = 0
const COMMAND_ECHO_VALUE = 1
const COMMAND_GET_KEY_INDEX = 1
const COMMAND_SET_KEY_INDEX = 1
const COMMAND_SET_VALUE_INDEX = 2
const COMMAND_SET_TIMEOUT_MODE_INDEX = 3
const COMMAND_SET_TIMEOUT_INDEX = 4
const COMMAND_EXISTS_KEY_INDEX = 1
const COMMAND_DELETE_KEY_INDEX = 1
const COMMAND_INCREMENT_KEY_INDEX = 1
const COMMAND_DECREMENT_KEY_INDEX = 1
const COMMAND_LPUSH_KEY_INDEX = 1
const COMMAND_LPUSH_VALUE_INDEX = 2
const COMMAND_RPUSH_KEY_INDEX = 1
const COMMAND_RPUSH_VALUE_INDEX = 2

const COMMAND_SET_TIMEOUT_MODE_EXPIRE_SECONDS = "EX"
const COMMAND_SET_TIMEOUT_MODE_EXPIRE_MILLISECONDS = "PX"
const COMMAND_SET_TIMEOUT_MODE_TIMESTAMP_SECONDS = "EXAT"
const COMMAND_SET_TIMEOUT_MODE_TIMESTAMP_MILLISECONDS = "PXAT"

const COMMAND_RESULT_OK = "OK"
const COMMAND_ERROR_FAILED_DESERIALIZATION = "ERR FAILED-DESERIALIZING"
const COMMAND_ERROR_UNEXPECTED_RESP_TYPES = "ERR UNEXPEC-RESP-TYPES"
const COMMAND_ERROR_INVALID_ARGUMENTS_NUMBER = "ERR INVALID-ARGUMENTS-NUMBER"
const COMMAND_ERROR_INVALID_COMMAND = "ERR INVALID-COMMAND"
const COMMAND_ERROR_UNRECOGNIZED_TIMEOUT_MODE = "ERR UNRECOGNIZED-TIMEOUT-MODE"
const COMMAND_ERROR_INVALID_TIMEOUT_VALUE = "ERR INVALID-TIMEOUT-VALUE"
const COMMAND_ERROR_VALUE_NOT_NUMERIC_OR_MAX_REACHED = "ERR VALUE-NOT-NUMERIC-OR-MAX-REACHED"
const COMMAND_ERROR_VALUE_NOT_A_LIST = "ERR VALUE-NOT-A-LIST"

type Command interface {
}

type SetCommand struct {
	key        string
	value      RespDataType
	rspChannel chan RespDataType
}

type GetCommand struct {
	key        string
	rspChannel chan RespDataType
}

type ExistsCommand struct {
	key        string
	rspChannel chan RespDataType
}

type DeleteCommand struct {
	key        string
	rspChannel chan RespDataType
}

type IncrementCommand struct {
	key        string
	rspChannel chan RespDataType
}

type DecrementCommand struct {
	key        string
	rspChannel chan RespDataType
}

type LPushCommand struct {
	key        string
	value      RespDataType
	rspChannel chan RespDataType
}

type RPushCommand struct {
	key        string
	value      RespDataType
	rspChannel chan RespDataType
}
